<<<<<<< HEAD
# Generated by Django 3.1.7 on 2021-08-22 18:38
=======
# Generated by Django 3.1.7 on 2021-08-22 21:30
>>>>>>> styletime

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=8)),
                ('size', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ebet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('bet', models.DecimalField(decimal_places=10, max_digits=25)),
                ('crypto', models.CharField(max_length=10)),
                ('payout', models.IntegerField(default=0)),
=======
                ('name', models.CharField(max_length=20)),
                ('start_amount', models.FloatField(default=10000)),
                ('room_code', models.CharField(max_length=8)),
                ('start_time', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('active', models.BooleanField(default=False)),
                ('e_bet', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=True)),
                ('options', models.BooleanField(default=True)),
                ('duration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.duration')),
>>>>>>> styletime
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_amount', models.FloatField(default=10000)),
                ('bet', models.FloatField(default=10000)),
                ('start_time', models.CharField(max_length=10)),
                ('positions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_host', models.BooleanField(default=False)),
                ('ready', models.BooleanField(default=False)),
                ('cash', models.DecimalField(decimal_places=4, max_digits=25, null=True)),
<<<<<<< HEAD
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.competition')),
=======
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
>>>>>>> styletime
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('competition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.competition')),
                ('start_amount', models.FloatField(default=10000)),
                ('start_time', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
                ('public', models.BooleanField(default=True)),
            ],
            bases=('game.competition',),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('competition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.competition')),
                ('round', models.CharField(default='day', max_length=4)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('options', models.BooleanField(default=True)),
            ],
            bases=('game.competition',),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought', models.BooleanField()),
                ('symbol', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=25)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('time', models.DecimalField(decimal_places=5, max_digits=15)),
                ('cash', models.DecimalField(decimal_places=4, max_digits=25)),
                ('total_quantity', models.DecimalField(decimal_places=10, max_digits=25)),
                ('positions', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.DecimalField(decimal_places=4, max_digits=25)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.history')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Holdings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=25)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='bet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.ebet'),
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='LongGame',
            fields=[
                ('game_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.game')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('options', models.BooleanField(default=True)),
            ],
            bases=('game.game',),
        ),
        migrations.CreateModel(
            name='ShortGame',
            fields=[
                ('game_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.game')),
                ('duration', models.IntegerField(default=0)),
=======
            name='Ebet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.DecimalField(decimal_places=10, max_digits=25)),
                ('crypto', models.CharField(max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
>>>>>>> styletime
            ],
            bases=('game.game',),
        ),
    ]
