# Generated by Django 3.2.5 on 2021-08-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='duration',
        ),
        migrations.AddField(
            model_name='game',
            name='end',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Duration',
        ),
    ]
