# Generated by Django 3.1.6 on 2021-07-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='contract',
            field=models.JSONField(default=dict),
        ),
    ]
