# Generated by Django 3.2.5 on 2021-08-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortgame',
            name='ready',
        ),
    ]
