# Generated by Django 3.2.5 on 2021-08-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210811_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='is_contract',
            new_name='e_bet',
        ),
    ]
