# Generated by Django 3.2.5 on 2021-08-20 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_shortgame_ready'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('competition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.competition')),
                ('round', models.CharField(default='day', max_length=4)),
            ],
            bases=('game.competition',),
        ),
        migrations.RemoveField(
            model_name='competition',
            name='min_size',
        ),
        migrations.AlterField(
            model_name='competition',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.competition'),
        ),
    ]
