# Generated by Django 3.2.5 on 2021-08-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210801_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cash',
            field=models.IntegerField(default=25000),
        ),
        migrations.AddField(
            model_name='transactions',
            name='positions',
            field=models.IntegerField(default=0),
        ),
    ]
