# Generated by Django 3.2.5 on 2021-08-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_is_contract_game_e_bet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='positions',
        ),
        migrations.AddField(
            model_name='game',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
