# Generated by Django 3.2.5 on 2021-08-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210820_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='options',
            field=models.BooleanField(default=True),
        ),
    ]
