# Generated by Django 3.2.5 on 2021-08-01 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('game', '0004_auto_20210801_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_amount', models.FloatField(default=10000)),
                ('bet', models.FloatField(default=10000)),
                ('start_time', models.CharField(max_length=10)),
                ('positions', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='cash',
            field=models.DecimalField(decimal_places=4, max_digits=25),
        ),
        migrations.CreateModel(
            name='PlayerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.DecimalField(decimal_places=4, max_digits=25)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.history')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
