# Generated by Django 3.2.5 on 2021-08-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210820_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='address',
        ),
        migrations.RemoveField(
            model_name='player',
            name='key',
        ),
    ]
