# Generated by Django 3.2.5 on 2021-08-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210811_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='end',
        ),
    ]
