# Generated by Django 3.2.5 on 2021-08-22 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20210820_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.DecimalField(decimal_places=10, max_digits=25)),
                ('coin', models.CharField(max_length=4)),
                ('payout', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='competition',
            name='bet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.bet'),
        ),
        migrations.DeleteModel(
            name='Ebet',
        ),
    ]
