# Generated by Django 3.2.5 on 2021-08-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20210801_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerhistory',
            name='color',
            field=models.CharField(default='', max_length=20),
        ),
    ]
