# Generated by Django 3.2.5 on 2021-08-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_game_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='bet',
        ),
        migrations.AddField(
            model_name='game',
            name='options',
            field=models.BooleanField(default=True),
        ),
    ]
