# Generated by Django 3.2.5 on 2021-08-12 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20210811_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=0)),
                ('hours', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.duration'),
        ),
    ]
