# Generated by Django 3.2.5 on 2021-08-12 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20210812_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.duration'),
        ),
    ]
