# Generated by Django 3.2.5 on 2021-08-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_ebet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.IntegerField(default=0),
        ),
    ]
