# Generated by Django 3.2.5 on 2021-08-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20210814_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='cash',
            field=models.DecimalField(decimal_places=4, max_digits=25, null=True),
        ),
    ]
