# Generated by Django 3.2.5 on 2021-07-28 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_amount', models.FloatField(default=25000)),
                ('verification_code', models.CharField(max_length=6)),
                ('holdings', models.JSONField(default=dict)),
                ('friends', models.JSONField(default=dict)),
                ('invites', models.JSONField(default=dict)),
                ('latest_path', models.CharField(default='/', max_length=25)),
                ('address', models.CharField(default='', max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought', models.BooleanField()),
                ('symbol', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=25)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('time', models.DecimalField(decimal_places=5, max_digits=15)),
                ('cash', models.DecimalField(decimal_places=4, max_digits=25)),
                ('total_quantity', models.DecimalField(decimal_places=10, max_digits=25)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
