# Generated by Django 3.1.6 on 2021-07-05 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_amount', models.FloatField(default=25000)),
                ('verification_code', models.CharField(max_length=6)),
                ('transactions', models.JSONField(default=dict)),
                ('holdings', models.JSONField(default=dict)),
                ('friends', models.JSONField(default=dict)),
                ('invites', models.JSONField(default=dict)),
                ('latest_path', models.CharField(default='/', max_length=100)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
