# Generated by Django 3.1.6 on 2021-07-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='latest_path',
            field=models.CharField(default='/', max_length=25),
        ),
    ]
