# Generated by Django 3.1.6 on 2021-03-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210301_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(max_length=6),
        ),
    ]
