export const USER_CREATED = 'USER_CREATED'
export const EMAIL_VERIFIED = 'EMAIL_VERIFIED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGGING_IN = 'LOGGING_IN'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const EMAIL_SENT = 'EMAIL_SENT'
export const RESET_SUCCESS = 'RESET_SUCCESS'
export const CHECK_SUCCESS = 'CHECK_SUCCESS'
export const ACTION_FAILED = 'ACTION_FAILED'
export const SEARCH_MADE = 'SEARCH_MADE'
export const LIST_LOADING = 'LIST_LOADING'
export const NO_SEARCH = 'NO_SEARCH'
export const SECURITY_LOADED = 'SECURITY_LOADED'
export const SECURITY_LOADING = 'SECURITY_LOADING'
export const SECURITY_UPDATED = 'SECURITY_UPDATED'
export const USER_LOADED = 'USER_LOADED'
export const USERS_LOADED = 'USERS_LOADED'
export const PORTFOLIO_LOADED = 'PORTFOLIO_LOADED'
export const HIDE_RESULTS = 'HIDE_RESULTS'
export const UPDATE_USER = 'UPDATE_USER'
export const FRIEND_LOADED = 'FRIEND_LOADED'
export const HISTORY_SAVED = 'HISTORY_SAVED'
export const GAME_CREATED = 'GAME_CREATED'
export const CREATING_GAME = 'CREATING_GAME'
export const GAME_LOADING = 'GAME_LOADING'
export const GAME_LOADED = 'GAME_LOADED'
export const NO_GAME = 'NO_GAME'
export const GAME_JOINED = 'GAME_JOINED'
export const HISTORY_LOADING = 'HISTORY_LOADING'
export const HISTORY_LOADED = 'HISTORY_LOADED'
export const NO_HISTORY = 'NO_HISTORY'
export const LOADING = 'LOADING'
export const LEADERBOARD_LOADED = 'LEADERBOARD_LOADED'
export const QUOTE_LOADED = 'QUOTE_LOADED'

// GAME
export const GAMES_LOADED = 'GAMES_LOADED'
export const GAME_INFO_LOADED = 'GAME_INFO_LOADED'
export const SEARCH_LOADED = 'SEARCH_LOADED'
export const MAKING_SEARCH = 'MAKING_SEARCH'


// SECURITIES
export const NEW_SECURITY = 'NEW_SECURITY'
export const OPTION_LOADED = 'OPTION_LOADED'
export const DATES_LOADED = 'DATES_LOADED'
export const LOADING_OPTION = 'LOADING_OPTION'

// PORTFOLIO
export const PORTFOLIO_LOADING = 'PORTFOLIO_LOADING'
export const DAY_LOADED = 'DAY_LOADED'
export const WEEK_LOADED = 'WEEK_LOADED'
export const MONTH_LOADED = 'MONTH_LOADED'
export const THREE_MONTH_LOADED = 'THREE_MONTH_LOADED'
export const YEAR_LOADED = 'YEAR_LOADED'
export const FIVE_YEAR_LOADED = 'FIVE_YEAR_LOADED'
export const FRIENDS_LOADED = 'FRIENDS_LOADED'
export const FRIENDS_LOADING = 'FRIENDS_LOADING'
export const CLEAR = 'CLEAR'


// USER
export const NO_USER = 'NO_USER'


// AUTH
export const CREATING_USER = 'CREATING_USER'
export const VERIFY_EMAIL = 'VERIFY_EMAIL'